import type { Metadata } from "next";
import { Providers } from "./providers";
import "./globals.css";

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Ticket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <header>
            <SignedOut>
              <SignInButton />
            </SignedOut>
          </header>
          <main>
            <SignedIn>
              <Providers>{children} </Providers>
            </SignedIn>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
